#ifndef DOCUMENTS_PROJECTS_POTATOS_SRC_GLOBAL_H_
#define DOCUMENTS_PROJECTS_POTATOS_SRC_GLOBAL_H_

// NOLINTNEXTLINE
#define UNUSED(x) (void) x

#define NULL 0

#endif  // DOCUMENTS_PROJECTS_POTATOS_SRC_GLOBAL_H_
